# Chapter 02: Preliminaries

## 2.1 Data Manipulation

#### `Tensor`s are similar to `ndarray`s in NumPy with some differences.
1. `Tensor`s support GPUs to accelerate computation whereas `ndarray`s support only CPU computation.
2. `Tensor`s support automatic differentiation.

#### These properties make the `Tensor` class suitable for Deep Learning.

### 2.1.1 Getting Started

#### A tensor represents a (possibly multi-dimensional) array of numerical values. With one axis, a tensor is called a *vector*. With two axes, a tensor is called a *matrix*. With $k > 2$ axes, we drop the specialized names and just refer to the object as a $k^{th}$ order tensor.

In [8]:
import torch

# torch.arange(n) => creates a vector of evenly spaced values
# starting at 0 (included) and ending at n (not included)
x = torch.arange(12, dtype=torch.float32)
print(f"x: \n{x}")

# tensorʼs shape (the length along each axis)
print(f"x.shape = {x.shape}")

# total number of elements in a tensor
print(f"x.numel() = {x.numel()}")

# reshape() => change the shape of a tensor
# without altering either the number of elements or their values
# row vector to matrix of shape (3, 4)
print(f"x.reshape(3, 4): \n{x.reshape(3, 4)}")

# Reshaping by manually specifying every dimension is unnecessary.
# Tensors can automatically work out one dimension given the rest.
# We invoke this capability by placing -1 for the dimension that we would like tensors to automatically infer.
print(f"x.reshape(3, -1): \n{x.reshape(3, -1)}")
print(f"x.reshape(-1, 4): \n{x.reshape(-1, 4)}")

# matrices initialized either with zeros, ones, or numbers randomly sampled from a specific distribution
print(f"torch.zeros((2, 3, 4)): \n{torch.zeros((2, 3, 4))}")
print(f"torch.ones((2, 3, 4)): \n{torch.ones((2, 3, 4))}")

# Each of the elements randomly sampled from a standard Gaussian
# (normal) distribution with a mean of 0 and a standard deviation of 1
print(f"torch.randn((2, 3, 4)): \n{torch.randn((2, 3, 4))}")

# Specify exact elements by supplying a list to torch.tensor()
x = torch.tensor([[1, 2, 3, 4], [2, 4, 1, 3], [4, 2, 3, 1]])
print(f"x: \n{x}")

x: 
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
x.shape = torch.Size([12])
x.numel() = 12
x.reshape(3, 4): 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
x.reshape(3, -1): 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
x.reshape(-1, 4): 
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
torch.zeros((2, 3, 4)): 
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.ones((2, 3, 4)): 
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.randn((2, 3, 4)): 
tensor([[[ 1.0919, -0.3940, -0.8393,  0.9235],
         [-0.7803, -2.4219, -2.4531, -1.6257],
         [ 2.6056,  0.5089,  1.8906, -2.4101]],

       