# Chapter 02: Preliminaries

## 2.1 Data Manipulation

### 2.1.1 Getting Started

In [1]:
import tensorflow as tf

# torch.arange(n) => creates a vector of evenly spaced values
# starting at 0 (included) and ending at n (not included)
x = tf.range(12, dtype=tf.float32)
print(f"x: \n{x}")

# tensorʼs shape (the length along each axis)
print(f"x.shape = {x.shape}")

# total number of elements in a tensor
print(f"tf.size(x) = {tf.size(x)}")

# reshape() => change the shape of a tensor
# without altering either the number of elements or their values
# row vector to matrix of shape (3, 4)
print(f"tf.reshape(x, (3, 4)): \n{tf.reshape(x, (3, 4))}")

# Reshaping by manually specifying every dimension is unnecessary.
# Tensors can automatically work out one dimension given the rest.
# We invoke this capability by placing -1 for the dimension that we would like tensors to automatically infer.
print(f"tf.reshape(x, (3, -1)): \n{tf.reshape(x, (3, -1))}")
print(f"tf.reshape(x, (-1, 4)): \n{tf.reshape(x, (-1, 4))}")

# matrices initialized either with zeros, ones, or numbers randomly sampled from a specific distribution
print(f"tf.zeros((2, 3, 4)): \n{tf.zeros((2, 3, 4))}")
print(f"tf.ones((2, 3, 4)): \n{tf.ones((2, 3, 4))}")

# Each of the elements randomly sampled from a standard Gaussian
# (normal) distribution with a mean of 0 and a standard deviation of 1
print(f"tf.random.normal(shape = [2, 3, 4]): \n{tf.random.normal(shape = [2, 3, 4])}")

# Specify exact elements by supplying a list to torch.tensor()
x = tf.constant([[1, 2, 3, 4], [2, 4, 1, 3], [4, 2, 3, 1]])
print(f"x: \n{x}")

2022-04-01 18:47:00.055299: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-01 18:47:00.055343: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-04-01 18:47:09.128066: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-04-01 18:47:09.128128: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-04-01 18:47:09.128169: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ancil-Aspire-E5-571): /proc/driver/nvidia/version does not exist
2022-04-01 18:47:09.151617: I tensorflow/core/platform/cp

x: 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
x.shape = (12,)
tf.size(x) = 12
tf.reshape(x, (3, 4)): 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tf.reshape(x, (3, -1)): 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tf.reshape(x, (-1, 4)): 
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tf.zeros((2, 3, 4)): 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
tf.ones((2, 3, 4)): 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
tf.random.normal(shape = [2, 3, 4]): 
[[[ 0.5839058   2.4547038  -1.1301433   1.2154073 ]
  [-0.31525     1.280252   -0.96664333 -0.80689776]
  [ 0.8099281  -0.09745093  1.1704886  -0.27800894]]

 [[-1.6139616   1.8401304  -1.4841629  -0.56467324]
  [-0.8258288   0.61258006  0.9799425  -1.7867311 ]
  [ 1.2026368   1.5435642   1.6035181   0.07866979]]]
x: 
[[1 2 3 4]
 [2 4 1 3]
 [4 2 3 1]]
